### ISSUE TITLE
Development TODO

### ISSUE THREAD

**Issue by Warriorrrr** [TownyAdvanced/TownyMenus#1]
Click Actions
----------------
- [x] back button
- [x] confirmation button
- [x] open menu button
- [x] runnable action
- [x] sound action
- [ ] paginator button

Town Menu
----------------
- [ ] Resident management menu (mayor/assistant)
  - [ ] Kick resident
  - [ ] Add/remove ranks
  - [ ] View resident info, i.e. last online/when they joined the town
  - [ ] Set resident title/surname
- [ ] Town info hover item
- [ ] /town bankhistory
- [ ] /town plots button
- [ ] /town deposit/withdraw button(s)
- [ ] /town spawn button, with optional confirm screen
- [ ] /town online menu
- [ ] /town set menu
  - [ ] Town name
  - [ ] Board
  - [ ] Spawn
- [ ] /town toggle menu
  - [ ] Toggle explosion/mobs/pvp/fire
  - [ ] Toggle open

Plot Menu
----------------
- [ ] new /plot trust menu
- [ ] /plot claim (confirm if price > 0 or part of a group)
- [ ] /plot set menu
  - [ ] Name
  - [ ] /plot set <type> menu
- [ ] /plot toggle <fire/explosion/mobs/pvp>
- [ ] /plot fs/nfs

Nation Menu
----------------
- [ ] /nation bankhistory
- [ ] /nation deposit/withdraw
- [ ] Nation rank management menu
- [ ] /nation spawn
- [ ] /nation toggle menu
  - [ ] /nation toggle open
  - [ ] /nation toggle public
- [ ] /nation set menu
  - [ ] /nation set spawn
  - [ ] /nation set name
  - [ ] Set resident nation title/surname
- [ ] /nation online

Resident Menu
----------------
- [ ] Resident friends menu
  - [ ] Ability to add/remove friends
  - [ ] View friend info by hovering over item
- [x] Resident info hover item
- [x] /resident spawn
